"""feat:neon migrate

Revision ID: a9279a491aa1
Revises: 
Create Date: 2024-07-06 13:56:49.820846

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a9279a491aa1'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('dashboard',
    sa.Column('id_dashboard', sa.Integer(), nullable=False),
    sa.Column('wind', sa.Float(), nullable=False),
    sa.Column('rainfall', sa.Float(), nullable=False),
    sa.Column('humidity', sa.Float(), nullable=False),
    sa.Column('temperature', sa.Float(), nullable=False),
    sa.Column('timeStamp', sa.String(length=250), nullable=False),
    sa.PrimaryKeyConstraint('id_dashboard')
    )
    op.create_table('realtime',
    sa.Column('id_realtime', sa.Integer(), nullable=False),
    sa.Column('hum', sa.Float(), nullable=False),
    sa.Column('soil_nitro', sa.Float(), nullable=False),
    sa.Column('soil_phos', sa.Float(), nullable=False),
    sa.Column('soil_pot', sa.Float(), nullable=False),
    sa.Column('soil_temp', sa.Float(), nullable=False),
    sa.Column('soil_ph', sa.Float(), nullable=False),
    sa.Column('temp', sa.Float(), nullable=False),
    sa.Column('timeStamp', sa.String(length=250), nullable=False),
    sa.PrimaryKeyConstraint('id_realtime')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('realtime')
    op.drop_table('dashboard')
    # ### end Alembic commands ###
